### ISSUE TITLE
Wired devices

### ISSUE THREAD

**Issue by barrettj** [irkit/device#8]
Despite joining my wifi, it doesn't appear any of my wired devices can access the local API - is this intentional or am I doing something wrong?  These wired devices can get a ping response, but not from the http server.

All of my devices that are connected to the wifi network can get a response.

**Comment by barrettj** [comment]
Nevermind, it seems to be working most of the time now.  Occasionally I'll get back an empty response from the server, but usually it works.

**Comment by wajidjameel6-eng** [comment]
>.

**Comment by wajidjameel6-eng** [comment]
Xiaomi

**Comment by wajidjameel6-eng** [comment]
>
